apiVersion: v1
kind: Pod
metadata:
  name: nginx-toleration
spec:
  tolerations:
  - key: "ready"
    operator: "Equal"
    value: "no"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx
