apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-pod-manager
  namespace: default    # 角色的权限限制在默认命名空间下
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "delete"]

