apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-deployment-pod-manager-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: my-sa
  namespace: default   # my-sa的命名空间
roleRef:
  kind: Role
  name: deployment-pod-manager
  apiGroup: rbac.authorization.k8s.io
