apiVersion: v1
kind: Pod
metadata:
  name: my-emptydir-pod
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:   # 容器nginx挂载Volume
    - name: data
      mountPath: /data
  - image: busybox
    name: busybox
    command: ["/bin/sh","-c","sleep 3600"]
    volumeMounts:   # 容器busybox挂载Volume
    - name: data
      mountPath: /data
  volumes:          # 定义了一个emptyDir类型Volume
  - name: data
    emptyDir:
      sizeLimit: 500Mi   # 可以限定emptyDir的容量
