apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod
  namespace: default
spec:
  containers:
  - name: busybox-c
    image: busybox   # busybox是一个linux工具包，可以执行shell命令
    command: ["/bin/sleep", "100"] # 执行程序休眠100秒
    env:
    - name: USERNAME   # 最终Pod里的环境变量名称
      valueFrom:
        secretKeyRef:
          name: my-secret  # 部署的Secret资源名称
          key: username   # Secret中定义的参数username
    - name: PASSWORD    # 最终Pod里的环境变量名称
      valueFrom:
        secretKeyRef:
          name: my-secret  # 部署的Secret资源名称
          key: password   # Secret中定义的参数password

