apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: default
type: Opaque  # 对应命令中的generic类型
data:
  username: YWRtaW4=
  password: MTIzNDU2
immutable: true  # immutable字段设置为 true，创建的Secret不可更改

