apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nfs-deployment
spec:
  selector:
    matchLabels:
      app: busybox-pod
  replicas: 3
  template:
    metadata:
      labels:
        app: busybox-pod
    spec:
      containers:
      - name: busybox-c
        image: busybox
        command: ["/bin/sh","-c","sleep 3600"]
        volumeMounts:
        - name: nfs-shared-data
          mountPath: /tmp/data
      volumes:
      - name: nfs-shared-data
        nfs:
          server: k8s-work2   # NFS服务器IP、域名或者主机名
          path: /nfs/k8s/shared   # 共享目录
